[build]
  publish = "dist"

# Redirects for main site and niver2025 section
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/niver2025/*"
  to = "/niver2025/index.html"
  status = 200 