[build]
  command = "npm run build:prod"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--experimental-modules"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# Assets do niver2025
[[redirects]]
  from = "/niver2025/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# API Routes - These must come BEFORE the SPA route
[[redirects]]
  from = "/niver2025/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Spotify Callback
[[redirects]]
  from = "/spotify/callback"
  to = "/.netlify/functions/spotify-callback"
  status = 200
  force = true

# Niver2025 Spotify Callback
[[redirects]]
  from = "/niver2025/callback"
  to = "/.netlify/functions/spotify-callback"
  status = 200
  force = true

# SPA Routes - This must come LAST
[[redirects]]
  from = "/niver2025/*"
  to = "/niver2025/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3001 