[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

# API Routes
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Spotify Callback
[[redirects]]
  from = "/spotify/callback"
  to = "/.netlify/functions/spotify-callback"
  status = 200

# Niver2025 Spotify Callback
[[redirects]]
  from = "/niver2025/callback"
  to = "/.netlify/functions/spotify-callback"
  status = 200

# SPA Routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3001
  targetPort = 3002 