[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[[redirects]]
  from = "/niver2025/callback"
  to = "/.netlify/functions/spotify-callback"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "."
  autoLaunch = true 